using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using DMToCSharp.Core;
using DMToCSharp.Core.AST;
using DMToCSharp.Semantics;

namespace DMToCSharp.Emitter
{
    public class CSharpEmitter : IDMASTVisitor<string>
    {
        private readonly DMObjectTree _objectTree;
        private readonly StringBuilder _sb = new StringBuilder();
        private int _indent = 0;
        private string _currentProcName = "";
        private List<DMASTProcParameter> _currentProcParams = new List<DMASTProcParameter>();
        private readonly HashSet<string> _currentLocalsAndParams = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        private DreamPath _currentTypePath = DreamPath.Root;

        public CSharpEmitter(DMObjectTree objectTree)
        {
            _objectTree = objectTree;
        }

        private void Indent() { _indent++; }
        private void Unindent() { if (_indent > 0) _indent--; }

        private void WriteLine(string line = "")
        {
            if (string.IsNullOrEmpty(line))
            {
                _sb.AppendLine();
                return;
            }
            _sb.Append(new string(' ', _indent * 4));
            _sb.AppendLine(line);
        }

        public string Emit()
        {
            _sb.Clear();

            WriteLine("// ==========================================================================");
            WriteLine("// Generated by DMToCSharp (DreamMaker to C# Transpiler)");
            WriteLine("// ==========================================================================");
            WriteLine("using System;");
            WriteLine("using System.Collections;");
            WriteLine("using System.Collections.Generic;");
            WriteLine("using DMToCSharp.Core;");
            WriteLine("using DMToCSharp.Runtime;");
            WriteLine();
            WriteLine("namespace DMCompiled");
            WriteLine("{");
            Indent();

            EmitGlobalVars();
            EmitGlobalProcs();
            EmitTypes();
            EmitEntryPoint();

            Unindent();
            WriteLine("}");

            return _sb.ToString();
        }

        private void EmitGlobalVars()
        {
            WriteLine("public static class GlobalVars");
            WriteLine("{");
            Indent();

            foreach (var kvp in _objectTree.GlobalVars)
            {
                var v = kvp.Value;
                string initVal = v.InitialValue != null ? v.InitialValue.Accept(this) : "DMValue.Null";
                string safeName = DreamPath.SanitizeIdentifier(v.Name);
                WriteLine(string.Format("public static DMValue {0} = {1};", safeName, initVal));
            }

            Unindent();
            WriteLine("}");
            WriteLine();
        }

        private void EmitGlobalProcs()
        {
            WriteLine("public static class GlobalProcs");
            WriteLine("{");
            Indent();

            _currentTypePath = DreamPath.Root;
            foreach (var kvp in _objectTree.GlobalProcs)
            {
                var proc = kvp.Value;
                EmitProcMethod(proc, isGlobal: true);
            }

            Unindent();
            WriteLine("}");
            WriteLine();
        }

        private void EmitTypes()
        {
            foreach (var kvp in _objectTree.Types)
            {
                DreamPath path = kvp.Key;
                DMTypeDefinition typeDef = kvp.Value;

                if (IsStandardBuiltinType(path))
                {
                    continue;
                }

                if (path == DreamPath.Root)
                    continue;

                _currentTypePath = path;
                string className = path.ToCSharpClassName();
                string baseClassName = "DMObject";

                if (typeDef.Parent != null && typeDef.Parent.Path != DreamPath.Root)
                {
                    if (IsStandardBuiltinType(typeDef.Parent.Path))
                    {
                        baseClassName = "DM_" + typeDef.Parent.Path.PathString.TrimStart('/').Replace('/', '_');
                    }
                    else
                    {
                        baseClassName = typeDef.Parent.Path.ToCSharpClassName();
                    }
                }

                WriteLine(string.Format("public class {0} : {1}", className, baseClassName));
                WriteLine("{");
                Indent();

                WriteLine(string.Format("public override DreamPath TypePath {{ get {{ return new DreamPath(\"{0}\"); }} }}", path.PathString));
                if (typeDef.Parent != null && typeDef.Parent.Path != DreamPath.Root)
                {
                    WriteLine(string.Format("public override DreamPath ParentTypePath {{ get {{ return new DreamPath(\"{0}\"); }} }}", typeDef.Parent.Path.PathString));
                }
                WriteLine();

                WriteLine(string.Format("public {0}()", className));
                WriteLine("{");
                Indent();
                WriteLine(string.Format("name = new DMValue(\"{0}\");", path.LastElement));
                foreach (var v in typeDef.Variables.Values)
                {
                    if (v.InitialValue != null && (v.Name == "name" || v.Name == "desc" || (path.IsDescendantOf(DreamPath.Atom) && (v.Name == "icon_state" || v.Name == "density" || v.Name == "opacity"))))
                    {
                        string safeName = DreamPath.SanitizeIdentifier(v.Name);
                        WriteLine(string.Format("{0} = {1};", safeName, v.InitialValue.Accept(this)));
                    }
                }
                Unindent();
                WriteLine("}");
                WriteLine();

                foreach (var v in typeDef.Variables.Values)
                {
                    if (v.Name == "name" || v.Name == "desc" || v.Name == "loc" || v.Name == "contents")
                        continue;
                    if (path.IsDescendantOf(DreamPath.Atom) && (v.Name == "icon_state" || v.Name == "density" || v.Name == "opacity"))
                        continue;

                    string initVal = v.InitialValue != null ? v.InitialValue.Accept(this) : "DMValue.Null";
                    string safeName = DreamPath.SanitizeIdentifier(v.Name);
                    WriteLine(string.Format("public DMValue {0} = {1};", safeName, initVal));
                }
                WriteLine();

                foreach (var proc in typeDef.Procs.Values)
                {
                    EmitProcMethod(proc, isGlobal: false);
                }

                Unindent();
                WriteLine("}");
                WriteLine();
            }
        }

        private bool IsStandardBuiltinType(DreamPath path)
        {
            return path == DreamPath.Root || path == DreamPath.Datum || path == DreamPath.Atom ||
                   path == DreamPath.Movable || path == DreamPath.Obj || path == DreamPath.Mob ||
                   path == DreamPath.Turf || path == DreamPath.Area || path == DreamPath.Client ||
                   path == DreamPath.World || path == DreamPath.List || path == DreamPath.Sound ||
                   path == DreamPath.Image || path == DreamPath.Icon || path == DreamPath.Matrix ||
                   path == DreamPath.Regex || path == DreamPath.Savefile;
        }

        private void EmitProcMethod(DMProcInfo proc, bool isGlobal)
        {
            _currentProcName = proc.Name;
            _currentProcParams = proc.Parameters;
            _currentLocalsAndParams.Clear();

            foreach (var p in proc.Parameters)
            {
                _currentLocalsAndParams.Add(p.Name);
            }
            CollectLocals(proc.Body);

            string safeName = DreamPath.SanitizeIdentifier(proc.Name);
            List<string> paramStrings = new List<string>();

            foreach (var p in proc.Parameters)
            {
                string pName = DreamPath.SanitizeIdentifier(p.Name);
                paramStrings.Add(string.Format("DMValue {0} = default(DMValue)", pName));
            }

            string paramList = string.Join(", ", paramStrings.ToArray());
            string modifier = isGlobal ? "public static" : (proc.IsOverride ? "public override" : "public virtual");

            if (proc.Name.Equals("New", StringComparison.OrdinalIgnoreCase))
            {
                modifier = "public override";
            }

            WriteLine(string.Format("{0} DMValue {1}({2})", modifier, safeName, paramList));
            WriteLine("{");
            Indent();

            foreach (var p in proc.Parameters)
            {
                if (p.DefaultValue != null)
                {
                    string pName = DreamPath.SanitizeIdentifier(p.Name);
                    WriteLine(string.Format("if ({0}.IsNull) {0} = {1};", pName, p.DefaultValue.Accept(this)));
                }
            }

            WriteLine("DMValue __dot = DMValue.Null;");

            if (proc.Body != null)
            {
                foreach (var stmt in proc.Body.Statements)
                {
                    string code = stmt.Accept(this);
                    if (!string.IsNullOrEmpty(code))
                    {
                        WriteLine(code);
                    }
                }
            }

            WriteLine("return __dot;");
            Unindent();
            WriteLine("}");
            WriteLine();
        }

        private void CollectLocals(DMASTNode node)
        {
            if (node == null) return;
            if (node is DMASTBlock)
            {
                foreach (var s in ((DMASTBlock)node).Statements) CollectLocals(s);
            }
            else if (node is DMASTVarDeclarationStatement)
            {
                _currentLocalsAndParams.Add(((DMASTVarDeclarationStatement)node).Name);
            }
            else if (node is DMASTForInStatement)
            {
                _currentLocalsAndParams.Add(((DMASTForInStatement)node).VarName);
                CollectLocals(((DMASTForInStatement)node).Body);
            }
            else if (node is DMASTForRangeStatement)
            {
                _currentLocalsAndParams.Add(((DMASTForRangeStatement)node).VarName);
                CollectLocals(((DMASTForRangeStatement)node).Body);
            }
            else if (node is DMASTForStandardStatement)
            {
                CollectLocals(((DMASTForStandardStatement)node).Initializer);
                CollectLocals(((DMASTForStandardStatement)node).Body);
            }
            else if (node is DMASTIfStatement)
            {
                CollectLocals(((DMASTIfStatement)node).ThenBranch);
                CollectLocals(((DMASTIfStatement)node).ElseBranch);
            }
            else if (node is DMASTWhileStatement)
            {
                CollectLocals(((DMASTWhileStatement)node).Body);
            }
            else if (node is DMASTDoWhileStatement)
            {
                CollectLocals(((DMASTDoWhileStatement)node).Body);
            }
            else if (node is DMASTTryCatchStatement)
            {
                var tc = (DMASTTryCatchStatement)node;
                if (!string.IsNullOrEmpty(tc.ExceptionVar)) _currentLocalsAndParams.Add(tc.ExceptionVar);
                CollectLocals(tc.TryBlock);
                CollectLocals(tc.CatchBlock);
            }
            else if (node is DMASTSwitchStatement)
            {
                foreach (var c in ((DMASTSwitchStatement)node).Cases) CollectLocals(c.Body);
            }
        }

        private void EmitEntryPoint()
        {
            WriteLine("public static class Program");
            WriteLine("{");
            Indent();
            WriteLine("public static int Main(string[] args)");
            WriteLine("{");
            Indent();
            WriteLine("DMWorld world = DMWorld.Instance;");
            WriteLine("world.name = new DMValue(\"DM App\");");
            WriteLine();
            WriteLine("try");
            WriteLine("{");
            Indent();

            DMTypeDefinition worldType;
            if (_objectTree.GlobalProcs.ContainsKey("main"))
            {
                WriteLine("GlobalProcs.main();");
            }
            else if (_objectTree.Types.TryGetValue(DreamPath.World, out worldType) && worldType.Procs.ContainsKey("New"))
            {
                WriteLine("world.New();");
            }
            else
            {
                WriteLine("world.Output(new DMValue(\"Compiled DreamMaker Program executed successfully.\"));");
            }

            Unindent();
            WriteLine("}");
            WriteLine("catch (Exception ex)");
            WriteLine("{");
            Indent();
            WriteLine("Console.WriteLine(\"Runtime Error: \" + ex.Message);");
            WriteLine("Console.WriteLine(ex.StackTrace);");
            WriteLine("return 1;");
            Unindent();
            WriteLine("}");
            WriteLine();
            WriteLine("return 0;");
            Unindent();
            WriteLine("}");
            Unindent();
            WriteLine("}");
        }

        // ================= VISITOR IMPLEMENTATIONS =================

        public string Visit(DMASTFile node) { return ""; }
        public string Visit(DMASTObjectDefinition node) { return ""; }
        public string Visit(DMASTVarDefinition node) { return ""; }
        public string Visit(DMASTProcDefinition node) { return ""; }
        public string Visit(DMASTProcParameter node) { return ""; }

        public string Visit(DMASTBlock node)
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("{");
            Indent();
            foreach (var stmt in node.Statements)
            {
                string code = stmt.Accept(this);
                if (!string.IsNullOrEmpty(code))
                {
                    sb.Append(new string(' ', _indent * 4));
                    sb.AppendLine(code);
                }
            }
            Unindent();
            sb.Append(new string(' ', _indent * 4));
            sb.Append("}");
            return sb.ToString();
        }

        public string Visit(DMASTExpressionStatement node)
        {
            string expr = node.Expression.Accept(this).Trim();
            while (expr.StartsWith("(") && expr.EndsWith(")") && HasMatchingOuterParens(expr))
            {
                expr = expr.Substring(1, expr.Length - 2).Trim();
            }
            return string.Format("{0};", expr);
        }

        private bool HasMatchingOuterParens(string s)
        {
            int depth = 0;
            for (int i = 0; i < s.Length - 1; i++)
            {
                if (s[i] == '(') depth++;
                else if (s[i] == ')')
                {
                    depth--;
                    if (depth == 0) return false;
                }
            }
            return depth == 1;
        }

        public string Visit(DMASTVarDeclarationStatement node)
        {
            string varName = DreamPath.SanitizeIdentifier(node.Name);
            string initVal = node.Initializer != null ? node.Initializer.Accept(this) : "DMValue.Null";
            return string.Format("DMValue {0} = {1};", varName, initVal);
        }

        public string Visit(DMASTIfStatement node)
        {
            string cond = node.Condition.Accept(this);
            StringBuilder sb = new StringBuilder();
            sb.Append(string.Format("if ({0}) ", cond));

            if (node.ThenBranch is DMASTBlock)
            {
                sb.AppendLine();
                sb.Append(new string(' ', _indent * 4));
                sb.Append(node.ThenBranch.Accept(this));
            }
            else
            {
                sb.AppendLine();
                Indent();
                sb.Append(new string(' ', _indent * 4));
                sb.Append(node.ThenBranch.Accept(this));
                Unindent();
            }

            if (node.ElseBranch != null)
            {
                sb.AppendLine();
                sb.Append(new string(' ', _indent * 4));
                sb.Append("else ");
                if (node.ElseBranch is DMASTBlock)
                {
                    sb.AppendLine();
                    sb.Append(new string(' ', _indent * 4));
                    sb.Append(node.ElseBranch.Accept(this));
                }
                else
                {
                    sb.AppendLine();
                    Indent();
                    sb.Append(new string(' ', _indent * 4));
                    sb.Append(node.ElseBranch.Accept(this));
                    Unindent();
                }
            }

            return sb.ToString();
        }

        public string Visit(DMASTWhileStatement node)
        {
            string cond = node.Condition.Accept(this);
            StringBuilder sb = new StringBuilder();
            sb.Append(string.Format("while ({0}) ", cond));
            sb.AppendLine();
            sb.Append(new string(' ', _indent * 4));
            sb.Append(node.Body.Accept(this));
            return sb.ToString();
        }

        public string Visit(DMASTDoWhileStatement node)
        {
            string cond = node.Condition.Accept(this);
            StringBuilder sb = new StringBuilder();
            sb.Append("do ");
            sb.AppendLine();
            sb.Append(new string(' ', _indent * 4));
            sb.Append(node.Body.Accept(this));
            sb.Append(string.Format(" while ({0});", cond));
            return sb.ToString();
        }

        public string Visit(DMASTForStandardStatement node)
        {
            string init = node.Initializer != null ? node.Initializer.Accept(this).TrimEnd(';') : "";
            string cond = node.Condition != null ? node.Condition.Accept(this) : "true";
            string incr = node.Increment != null ? node.Increment.Accept(this) : "";

            StringBuilder sb = new StringBuilder();
            sb.Append(string.Format("for ({0}; {1}; {2}) ", init, cond, incr));
            sb.AppendLine();
            sb.Append(new string(' ', _indent * 4));
            sb.Append(node.Body.Accept(this));
            return sb.ToString();
        }

        public string Visit(DMASTForInStatement node)
        {
            string varName = DreamPath.SanitizeIdentifier(node.VarName);
            string container = node.Container.Accept(this);

            StringBuilder sb = new StringBuilder();
            sb.AppendLine(string.Format("foreach (DMValue {0} in {1})", varName, container));
            sb.Append(new string(' ', _indent * 4));
            sb.Append(node.Body.Accept(this));
            return sb.ToString();
        }

        public string Visit(DMASTForRangeStatement node)
        {
            string varName = DreamPath.SanitizeIdentifier(node.VarName);
            string start = node.Start.Accept(this);
            string end = node.End.Accept(this);
            string step = node.Step != null ? node.Step.Accept(this) : "1";

            StringBuilder sb = new StringBuilder();
            sb.AppendLine(string.Format("for (DMValue {0} = {1}; {0} <= {2}; {0} += {3})", varName, start, end, step));
            sb.Append(new string(' ', _indent * 4));
            sb.Append(node.Body.Accept(this));
            return sb.ToString();
        }

        public string Visit(DMASTSwitchStatement node)
        {
            string val = node.Value.Accept(this);
            StringBuilder sb = new StringBuilder();
            sb.AppendLine(string.Format("DMValue __sw_val = {0};", val));
            sb.Append(new string(' ', _indent * 4));

            bool first = true;
            foreach (var c in node.Cases)
            {
                if (c.IsDefault)
                {
                    sb.AppendLine(first ? "{" : "else {");
                    Indent();
                    sb.Append(new string(' ', _indent * 4));
                    sb.AppendLine(c.Body.Accept(this));
                    Unindent();
                    sb.Append(new string(' ', _indent * 4));
                    sb.Append("}");
                }
                else
                {
                    List<string> conds = new List<string>();
                    foreach (var v in c.Values)
                    {
                        conds.Add(string.Format("(__sw_val == {0})", v.Accept(this)));
                    }
                    string condStr = string.Join(" || ", conds.ToArray());
                    sb.AppendLine((first ? "" : "else ") + string.Format("if ({0})", condStr));
                    sb.Append(new string(' ', _indent * 4));
                    sb.Append(c.Body.Accept(this));
                }
                first = false;
            }

            return sb.ToString();
        }

        public string Visit(DMASTCaseClause node) { return ""; }

        public string Visit(DMASTReturnStatement node)
        {
            string val = node.Value != null ? node.Value.Accept(this) : "__dot";
            return string.Format("return {0};", val);
        }

        public string Visit(DMASTBreakStatement node) { return "break;"; }
        public string Visit(DMASTContinueStatement node) { return "continue;"; }

        public string Visit(DMASTSpawnStatement node)
        {
            string delay = node.Delay != null ? node.Delay.Accept(this) : "0";
            StringBuilder sb = new StringBuilder();
            sb.AppendLine(string.Format("DMBuiltins.spawn({0}, delegate", delay));
            sb.Append(new string(' ', _indent * 4));
            sb.Append(node.Body.Accept(this));
            sb.Append(");");
            return sb.ToString();
        }

        public string Visit(DMASTTryCatchStatement node)
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("try");
            sb.Append(new string(' ', _indent * 4));
            sb.AppendLine(node.TryBlock.Accept(this));
            sb.Append(new string(' ', _indent * 4));
            string exVar = !string.IsNullOrEmpty(node.ExceptionVar) ? DreamPath.SanitizeIdentifier(node.ExceptionVar) : "__ex";
            sb.AppendLine(string.Format("catch (Exception {0}_raw)", exVar));
            sb.Append(new string(' ', _indent * 4));
            sb.AppendLine("{");
            Indent();
            sb.Append(new string(' ', _indent * 4));
            sb.AppendLine(string.Format("DMValue {0} = new DMValue({0}_raw.Message);", exVar));
            sb.Append(new string(' ', _indent * 4));
            sb.AppendLine(node.CatchBlock.Accept(this));
            Unindent();
            sb.Append(new string(' ', _indent * 4));
            sb.Append("}");
            return sb.ToString();
        }

        public string Visit(DMASTDelStatement node)
        {
            string target = node.Target.Accept(this);
            return string.Format("{0}.CallProc(\"Del\");", target);
        }

        public string Visit(DMASTGotoStatement node) { return string.Format("goto {0};", node.Label); }
        public string Visit(DMASTLabelStatement node) { return string.Format("{0}:", node.Label); }

        // ================= EXPRESSIONS =================

        public string Visit(DMASTConstantNull node) { return "DMValue.Null"; }
        public string Visit(DMASTConstantNumber node) { return string.Format("(DMValue){0}", node.Value.ToString(System.Globalization.CultureInfo.InvariantCulture)); }
        public string Visit(DMASTConstantString node) { return string.Format("(DMValue)\"{0}\"", EscapeCSharpString(node.Value)); }
        public string Visit(DMASTConstantResource node) { return string.Format("DMValue.CreateResource(\"{0}\")", EscapeCSharpString(node.Path)); }
        public string Visit(DMASTConstantPath node) { return string.Format("new DMValue(new DreamPath(\"{0}\"))", node.Path.PathString); }

        public string Visit(DMASTIdentifier node)
        {
            string id = node.Identifier;
            if (id == ".") return "__dot";
            if (id == "usr") return "((DMValue)this)";
            if (id == "src") return "((DMValue)this)";
            if (id == "world") return "DMWorld.Instance";
            if (id == "args") return "new DMValue(new DMList())";

            if (_objectTree.GlobalVars.ContainsKey(id))
            {
                return string.Format("GlobalVars.{0}", DreamPath.SanitizeIdentifier(id));
            }

            if (_currentLocalsAndParams.Contains(id))
            {
                return DreamPath.SanitizeIdentifier(id);
            }

            if (_currentTypePath != DreamPath.Root)
            {
                return string.Format("this.GetVar(\"{0}\")", id);
            }

            return DreamPath.SanitizeIdentifier(id);
        }

        public string Visit(DMASTUnaryExpression node)
        {
            if (node.Operand is DMASTIdentifier)
            {
                DMASTIdentifier idNode = (DMASTIdentifier)node.Operand;
                string id = idNode.Identifier;
                if (!_currentLocalsAndParams.Contains(id) && !_objectTree.GlobalVars.ContainsKey(id) && _currentTypePath != DreamPath.Root)
                {
                    if (node.Operator == UnaryOperator.PostDecrement || node.Operator == UnaryOperator.PreDecrement)
                        return string.Format("this.SetVar(\"{0}\", (this.GetVar(\"{0}\") - (DMValue)1))", id);
                    if (node.Operator == UnaryOperator.PostIncrement || node.Operator == UnaryOperator.PreIncrement)
                        return string.Format("this.SetVar(\"{0}\", (this.GetVar(\"{0}\") + (DMValue)1))", id);
                }
            }

            if (node.Operand is DMASTMemberAccessExpression)
            {
                DMASTMemberAccessExpression mem = (DMASTMemberAccessExpression)node.Operand;
                string target = mem.Target.Accept(this);
                string member = mem.Member;
                if (node.Operator == UnaryOperator.PostDecrement || node.Operator == UnaryOperator.PreDecrement)
                    return string.Format("{0}.SetVar(\"{1}\", ({0}.GetVar(\"{1}\") - (DMValue)1))", target, member);
                if (node.Operator == UnaryOperator.PostIncrement || node.Operator == UnaryOperator.PreIncrement)
                    return string.Format("{0}.SetVar(\"{1}\", ({0}.GetVar(\"{1}\") + (DMValue)1))", target, member);
            }

            string op = node.Operand.Accept(this);
            switch (node.Operator)
            {
                case UnaryOperator.Not: return string.Format("(!{0})", op);
                case UnaryOperator.Negate: return string.Format("(-{0})", op);
                case UnaryOperator.BitwiseNot: return string.Format("(~{0})", op);
                case UnaryOperator.PreIncrement: return string.Format("(++{0})", op);
                case UnaryOperator.PreDecrement: return string.Format("(--{0})", op);
                case UnaryOperator.PostIncrement: return string.Format("({0}++)", op);
                case UnaryOperator.PostDecrement: return string.Format("({0}--)", op);
                default: return op;
            }
        }

        public string Visit(DMASTBinaryExpression node)
        {
            string left = node.Left.Accept(this);
            string right = node.Right.Accept(this);

            if (node.Operator == BinaryOperator.In)
            {
                return string.Format("({0}.In({1}))", left, right);
            }

            if (node.Operator == BinaryOperator.ShiftLeft)
            {
                if (left.Contains("DMWorld.Instance") || left == "world")
                {
                    return string.Format("DMBuiltins.world_output({0})", right);
                }
            }

            string opSymbol = GetBinaryOpSymbol(node.Operator);
            return string.Format("({0} {1} {2})", left, opSymbol, right);
        }

        public string Visit(DMASTAssignExpression node)
        {
            if (node.Left is DMASTIndexAccessExpression)
            {
                DMASTIndexAccessExpression idx = (DMASTIndexAccessExpression)node.Left;
                string target = idx.Target.Accept(this);
                string index = idx.Index.Accept(this);
                string rightVal = node.Right.Accept(this);

                if (node.Operator == AssignmentOperator.Assign)
                    return string.Format("DMBuiltins.set_index({0}, {1}, {2})", target, index, rightVal);
                if (node.Operator == AssignmentOperator.AddAssign)
                    return string.Format("DMBuiltins.set_index({0}, {1}, (DMBuiltins.get_index({0}, {1}) + {2}))", target, index, rightVal);
                if (node.Operator == AssignmentOperator.SubtractAssign)
                    return string.Format("DMBuiltins.set_index({0}, {1}, (DMBuiltins.get_index({0}, {1}) - {2}))", target, index, rightVal);
            }

            if (node.Left is DMASTMemberAccessExpression)
            {
                DMASTMemberAccessExpression mem = (DMASTMemberAccessExpression)node.Left;
                string target = mem.Target.Accept(this);
                string member = mem.Member;
                string rightVal = node.Right.Accept(this);

                if (node.Operator == AssignmentOperator.Assign)
                    return string.Format("{0}.SetVar(\"{1}\", {2})", target, member, rightVal);
                if (node.Operator == AssignmentOperator.AddAssign)
                    return string.Format("{0}.SetVar(\"{1}\", ({0}.GetVar(\"{1}\") + {2}))", target, member, rightVal);
                if (node.Operator == AssignmentOperator.SubtractAssign)
                    return string.Format("{0}.SetVar(\"{1}\", ({0}.GetVar(\"{1}\") - {2}))", target, member, rightVal);
                if (node.Operator == AssignmentOperator.MultiplyAssign)
                    return string.Format("{0}.SetVar(\"{1}\", ({0}.GetVar(\"{1}\") * {2}))", target, member, rightVal);
                if (node.Operator == AssignmentOperator.DivideAssign)
                    return string.Format("{0}.SetVar(\"{1}\", ({0}.GetVar(\"{1}\") / {2}))", target, member, rightVal);
            }

            if (node.Left is DMASTIdentifier)
            {
                DMASTIdentifier idNode = (DMASTIdentifier)node.Left;
                string id = idNode.Identifier;
                if (!_currentLocalsAndParams.Contains(id) && !_objectTree.GlobalVars.ContainsKey(id) && _currentTypePath != DreamPath.Root)
                {
                    string rightVal = node.Right.Accept(this);
                    if (node.Operator == AssignmentOperator.Assign)
                        return string.Format("this.SetVar(\"{0}\", {1})", id, rightVal);
                    if (node.Operator == AssignmentOperator.AddAssign)
                        return string.Format("this.SetVar(\"{0}\", (this.GetVar(\"{0}\") + {1}))", id, rightVal);
                    if (node.Operator == AssignmentOperator.SubtractAssign)
                        return string.Format("this.SetVar(\"{0}\", (this.GetVar(\"{0}\") - {1}))", id, rightVal);
                    if (node.Operator == AssignmentOperator.MultiplyAssign)
                        return string.Format("this.SetVar(\"{0}\", (this.GetVar(\"{0}\") * {1}))", id, rightVal);
                    if (node.Operator == AssignmentOperator.DivideAssign)
                        return string.Format("this.SetVar(\"{0}\", (this.GetVar(\"{0}\") / {1}))", id, rightVal);
                }
            }

            string left = node.Left.Accept(this);
            string right = node.Right.Accept(this);
            string opSymbol = GetAssignOpSymbol(node.Operator);
            return string.Format("{0} {1} {2}", left, opSymbol, right);
        }

        public string Visit(DMASTCallExpression node)
        {
            List<string> args = new List<string>();
            foreach (var a in node.Arguments)
            {
                args.Add(a.Value.Accept(this));
            }
            string argList = string.Join(", ", args.ToArray());

            if (node.Target == null && IsBuiltinProc(node.ProcName))
            {
                return string.Format("DMBuiltins.{0}({1})", node.ProcName, argList);
            }

            if (node.Target != null)
            {
                string target = node.Target.Accept(this);
                return string.Format("{0}.CallProc(\"{1}\", new DMValue[] {{ {2} }})", target, node.ProcName, argList);
            }

            if (_currentTypePath == DreamPath.Root)
            {
                return string.Format("GlobalProcs.{0}({1})", DreamPath.SanitizeIdentifier(node.ProcName), argList);
            }

            if (_objectTree.GlobalProcs.ContainsKey(node.ProcName))
            {
                return string.Format("GlobalProcs.{0}({1})", DreamPath.SanitizeIdentifier(node.ProcName), argList);
            }

            return string.Format("this.{0}({1})", DreamPath.SanitizeIdentifier(node.ProcName), argList);
        }

        public string Visit(DMASTSuperCallExpression node)
        {
            List<string> pass = new List<string>();
            if (node.PassAllArgs || node.Arguments == null || node.Arguments.Count == 0)
            {
                foreach (var p in _currentProcParams)
                {
                    pass.Add(DreamPath.SanitizeIdentifier(p.Name));
                }
            }
            else
            {
                foreach (var a in node.Arguments)
                {
                    pass.Add(a.Value.Accept(this));
                }
            }

            DMTypeDefinition curDef;
            DMProcInfo parentProc;
            bool parentHasProc = _objectTree.Types.TryGetValue(_currentTypePath, out curDef) &&
                                 curDef.Parent != null &&
                                 curDef.Parent.TryGetProc(_currentProcName, out parentProc) &&
                                 !IsStandardBuiltinType(curDef.Parent.Path);

            if (parentHasProc)
            {
                return string.Format("base.{0}({1})", DreamPath.SanitizeIdentifier(_currentProcName), string.Join(", ", pass.ToArray()));
            }
            else
            {
                return string.Format("base.CallProc(\"{0}\", new DMValue[] {{ {1} }})", _currentProcName, string.Join(", ", pass.ToArray()));
            }
        }

        public string Visit(DMASTMemberAccessExpression node)
        {
            string target = node.Target.Accept(this);
            string member = node.Member;

            if (target == "DMWorld.Instance" || target.Contains("world"))
            {
                return string.Format("DMWorld.Instance.GetVar(\"{0}\")", member);
            }

            return string.Format("{0}.GetVar(\"{1}\")", target, member);
        }

        public string Visit(DMASTIndexAccessExpression node)
        {
            string target = node.Target.Accept(this);
            string index = node.Index.Accept(this);
            return string.Format("{0}[{1}]", target, index);
        }

        public string Visit(DMASTNewExpression node)
        {
            List<string> args = new List<string>();
            foreach (var a in node.Arguments)
            {
                args.Add(a.Value.Accept(this));
            }
            string argList = string.Join(", ", args.ToArray());

            if (node.TypePath is DMASTConstantPath)
            {
                DMASTConstantPath cp = (DMASTConstantPath)node.TypePath;
                string className = cp.Path.ToCSharpClassName();
                if (IsStandardBuiltinType(cp.Path))
                {
                    className = "DM_" + cp.Path.PathString.TrimStart('/').Replace('/', '_');
                }
                return string.Format("(new DMValue(new {0}().InitAndNew({1})))", className, argList);
            }
            if (node.TypePath != null)
            {
                return string.Format("(new DMValue(new DMObject().InitAndNew({0})))", argList);
            }

            return string.Format("(new DMValue(new DMObject().InitAndNew({0})))", argList);
        }

        public string Visit(DMASTTernaryExpression node)
        {
            string cond = node.Condition.Accept(this);
            string t = node.TrueValue.Accept(this);
            string f = node.FalseValue.Accept(this);
            return string.Format("({0} ? {1} : {2})", cond, t, f);
        }

        public string Visit(DMASTListExpression node)
        {
            List<string> items = new List<string>();
            foreach (var a in node.Elements)
            {
                if (a.Value is DMASTAssignExpression)
                {
                    DMASTAssignExpression assign = (DMASTAssignExpression)a.Value;
                    string key = assign.Left.Accept(this);
                    string val = assign.Right.Accept(this);
                    items.Add(string.Format("DMBuiltins.list_pair({0}, {1})", key, val));
                }
                else
                {
                    items.Add(a.Value.Accept(this));
                }
            }
            string argList = string.Join(", ", items.ToArray());
            return string.Format("DMBuiltins.list_init(new object[] {{ {0} }})", argList);
        }

        public string Visit(DMASTInterpolatedString node)
        {
            List<string> parts = new List<string>();
            foreach (var p in node.Parts)
            {
                if (p.IsExpression)
                {
                    parts.Add(p.Expression.Accept(this));
                }
                else
                {
                    parts.Add(string.Format("\"{0}\"", EscapeCSharpString(p.Text)));
                }
            }
            return string.Format("DMValue.Format({0})", string.Join(", ", parts.ToArray()));
        }

        public string Visit(DMASTLocateExpression node)
        {
            if (node.X != null && node.Y != null && node.Z != null)
            {
                return string.Format("DMBuiltins.locate({0}, {1}, {2})", node.X.Accept(this), node.Y.Accept(this), node.Z.Accept(this));
            }
            string first = node.TypeOrTag.Accept(this);
            string second = node.InContainer != null ? node.InContainer.Accept(this) : "DMValue.Null";
            return string.Format("DMBuiltins.locate({0}, {1})", first, second);
        }

        public string Visit(DMASTInputExpression node)
        {
            return "new DMValue(\"\")";
        }

        private bool IsBuiltinProc(string name)
        {
            return name == "istype" || name == "isnum" || name == "istext" || name == "islist" ||
                   name == "isloc" || name == "isnull" || name == "length" || name == "copytext" ||
                   name == "findtext" || name == "uppertext" || name == "lowertext" || name == "num2text" ||
                   name == "text2num" || name == "splittext" || name == "jointext" || name == "replacetext" ||
                   name == "ascii2text" || name == "text2ascii" || name == "round" || name == "abs" ||
                   name == "sqrt" || name == "sin" || name == "cos" || name == "min" || name == "max" ||
                   name == "prob" || name == "rand" || name == "roll" || name == "pick" || name == "sleep" ||
                   name == "spawn" || name == "list" || name == "locate" || name == "initial" || name == "alert" ||
                   name == "range" || name == "orange" || name == "view" || name == "oview" ||
                   name == "get_dist" || name == "get_dir" || name == "get_step" || name == "step" ||
                   name == "call_ext" || name == "load_map";
        }

        private string GetBinaryOpSymbol(BinaryOperator op)
        {
            switch (op)
            {
                case BinaryOperator.Add: return "+";
                case BinaryOperator.Subtract: return "-";
                case BinaryOperator.Multiply: return "*";
                case BinaryOperator.Divide: return "/";
                case BinaryOperator.Modulo: return "%";
                case BinaryOperator.Equal: return "==";
                case BinaryOperator.NotEqual: return "!=";
                case BinaryOperator.Equivalent: return "==";
                case BinaryOperator.NotEquivalent: return "!=";
                case BinaryOperator.Less: return "<";
                case BinaryOperator.LessOrEqual: return "<=";
                case BinaryOperator.Greater: return ">";
                case BinaryOperator.GreaterOrEqual: return ">=";
                case BinaryOperator.LogicalAnd: return "&&";
                case BinaryOperator.LogicalOr: return "||";
                case BinaryOperator.BitwiseAnd: return "&";
                case BinaryOperator.BitwiseOr: return "|";
                case BinaryOperator.BitwiseXor: return "^";
                case BinaryOperator.ShiftLeft: return "<<";
                case BinaryOperator.ShiftRight: return ">>";
                default: return "+";
            }
        }

        private string GetAssignOpSymbol(AssignmentOperator op)
        {
            switch (op)
            {
                case AssignmentOperator.Assign: return "=";
                case AssignmentOperator.AddAssign: return "+=";
                case AssignmentOperator.SubtractAssign: return "-=";
                case AssignmentOperator.MultiplyAssign: return "*=";
                case AssignmentOperator.DivideAssign: return "/=";
                case AssignmentOperator.ModuloAssign: return "%=";
                case AssignmentOperator.BitwiseAndAssign: return "&=";
                case AssignmentOperator.BitwiseOrAssign: return "|=";
                case AssignmentOperator.BitwiseXorAssign: return "^=";
                case AssignmentOperator.ShiftLeftAssign: return "<<=";
                case AssignmentOperator.ShiftRightAssign: return ">>=";
                default: return "=";
            }
        }

        private string EscapeCSharpString(string s)
        {
            if (string.IsNullOrEmpty(s)) return "";
            return s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r").Replace("\t", "\\t");
        }
    }
}
