// ==========================================================================
// Generated by DMToCSharp (DreamMaker to C# Transpiler)
// ==========================================================================
using System;
using System.Collections;
using System.Collections.Generic;
using DMToCSharp.Core;
using DMToCSharp.Runtime;

namespace DMCompiled
{
    public static class GlobalVars
    {
        public static DMValue server_name = (DMValue)"DreamMaker Station";
        public static DMValue round_id = (DMValue)42;
    }

    public static class GlobalProcs
    {
        public static DMValue add_numbers(DMValue a = default(DMValue), DMValue b = default(DMValue))
        {
            return (a + b);
            return DMValue.Null;
        }

        public static DMValue main()
        {
            DMBuiltins.world_output((DMValue)"=== DreamMaker Basics Test ===");
            DMBuiltins.world_output(DMValue.Format("Server: ", GlobalVars.server_name, ", Round: ", GlobalVars.round_id));
            DMValue x = (DMValue)10;
            DMValue y = (DMValue)25;
            DMValue sum = GlobalProcs.add_numbers(x, y);
            DMBuiltins.world_output(DMValue.Format("10 + 25 = ", sum));
            DMValue str = (((DMValue)"Space" + (DMValue)" ") + (DMValue)"Station");
            DMBuiltins.world_output(DMValue.Format("String concat: ", str));
            DMValue flt = (DMValue)3.14159;
            DMValue rounded = DMBuiltins.round(flt, (DMValue)0.01);
            DMBuiltins.world_output(DMValue.Format("PI rounded: ", rounded));
            DMBuiltins.world_output((DMValue)"Basics test completed successfully!");
            return DMValue.Null;
        }

    }

    public static class Program
    {
        public static int Main(string[] args)
        {
            DMWorld world = DMWorld.Instance;
            world.name = new DMValue("DM App");

            try
            {
                GlobalProcs.main();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Runtime Error: " + ex.Message);
                Console.WriteLine(ex.StackTrace);
                return 1;
            }

            return 0;
        }
    }
}
