// ==========================================================================
// Generated by DMToCSharp (DreamMaker to C# Transpiler)
// ==========================================================================
using System;
using System.Collections;
using System.Collections.Generic;
using DMToCSharp.Core;
using DMToCSharp.Runtime;

namespace DMCompiled
{
    public static class GlobalVars
    {
    }

    public static class GlobalProcs
    {
        public static DMValue main()
        {
            DMBuiltins.world_output((DMValue)"=== DM Inheritance & Polymorphism Test ===");
            DMValue cap = (new DMObject().New());
            DMBuiltins.world_output(cap.CallProc("describe", new DMValue[] {  }));
            cap.CallProc("take_damage", new DMValue[] { (DMValue)15 });
            DMValue is_mob = DMBuiltins.istype(cap, new DMValue(new DreamPath("/mob")));
            DMValue is_datum = DMBuiltins.istype(cap, new DMValue(new DreamPath("/datum")));
            DMBuiltins.world_output(DMValue.Format("Is mob: ", is_mob, ", Is datum: ", is_datum));
            DMBuiltins.world_output((DMValue)"Inheritance test completed!");
            return DMValue.Null;
        }

    }

    public class DM_datum_entity : DM_datum
    {
        public override DreamPath TypePath { get { return new DreamPath("/datum/entity"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/datum"); } }

        public DM_datum_entity()
        {
            name = new DMValue("entity");
        }

        public DMValue _ = (DMValue)100;

        public virtual DMValue describe()
        {
            return DMValue.Format("Entity: ", this.GetVar("name"), " (HP: ", this.GetVar("health"), ")");
            return DMValue.Null;
        }

        public virtual DMValue take_damage(DMValue amount = default(DMValue))
        {
            this.SetVar("health", (this.GetVar("health") - amount));
            DMBuiltins.world_output(DMValue.Format(this.GetVar("name"), " takes ", amount, " damage! Remaining: ", this.GetVar("health")));
            return this.GetVar("health");
            return DMValue.Null;
        }

    }

    public class DM_mob_human : DM_mob
    {
        public override DreamPath TypePath { get { return new DreamPath("/mob/human"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/mob"); } }

        public DM_mob_human()
        {
            name = new DMValue("human");
            name = (DMValue)"Human Crewmember";
        }

        public DMValue _ = (DMValue)"Assistant";

        public virtual DMValue describe()
        {
            DMValue @base = base.CallProc("describe", new DMValue[] {  });
            return DMValue.Format(@base, " | Job: ", this.GetVar("job"));
            return DMValue.Null;
        }

        public virtual DMValue take_damage(DMValue amount = default(DMValue))
        {
            DMBuiltins.world_output((DMValue)"Human flinches!");
            return base.CallProc("take_damage", new DMValue[] { amount });
            return DMValue.Null;
        }

    }

    public class DM_mob_human_captain : DM_mob_human
    {
        public override DreamPath TypePath { get { return new DreamPath("/mob/human/captain"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/mob/human"); } }

        public DM_mob_human_captain()
        {
            name = new DMValue("captain");
            name = (DMValue)"Station Captain";
        }

        public DMValue job = (DMValue)"Captain";
        public DMValue _ = (DMValue)5;

        public override DMValue describe()
        {
            DMValue @base = base.describe();
            return DMValue.Format(@base, " | Access: ", this.GetVar("access_level"));
            return DMValue.Null;
        }

    }

    public static class Program
    {
        public static int Main(string[] args)
        {
            DMWorld world = DMWorld.Instance;
            world.name = new DMValue("DM App");

            try
            {
                GlobalProcs.main();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Runtime Error: " + ex.Message);
                Console.WriteLine(ex.StackTrace);
                return 1;
            }

            return 0;
        }
    }
}
