// ==========================================================================
// Generated by DMToCSharp (DreamMaker to C# Transpiler)
// ==========================================================================
using System;
using System.Collections;
using System.Collections.Generic;
using DMToCSharp.Core;
using DMToCSharp.Runtime;

namespace DMCompiled
{
    public static class GlobalVars
    {
    }

    public static class GlobalProcs
    {
        public static DMValue main()
        {
            DMValue __dot = DMValue.Null;
            DMBuiltins.world_output((DMValue)"=== DM Lists Test ===");
            DMValue crew = DMBuiltins.list_init(new object[] { (DMValue)"Alice", (DMValue)"Bob", (DMValue)"Charlie", (DMValue)"David" });
            DMBuiltins.world_output(DMValue.Format("Crew count: ", crew.GetVar("len")));
            crew.CallProc("Add", new DMValue[] { (DMValue)"Eve" });
            DMBuiltins.world_output(DMValue.Format("Added Eve, new length: ", crew.GetVar("len")));
            DMValue first = crew[(DMValue)1];
            DMValue third = crew[(DMValue)3];
            DMBuiltins.world_output(DMValue.Format("First: ", first, ", Third: ", third));
            DMValue joined = DMBuiltins.jointext(crew, (DMValue)", ");
            DMBuiltins.world_output(DMValue.Format("Joined crew: ", joined));
            DMValue found = crew.CallProc("Find", new DMValue[] { (DMValue)"Charlie" });
            DMBuiltins.world_output(DMValue.Format("Index of Charlie: ", found));
            DMValue roles = DMBuiltins.list_init(new object[] { DMBuiltins.list_pair((DMValue)"Alice", (DMValue)"Engineer"), DMBuiltins.list_pair((DMValue)"Bob", (DMValue)"Doctor") });
            roles[(DMValue)"Charlie"] = (DMValue)"Clown";
            DMBuiltins.world_output(DMValue.Format("Charlie's role: ", roles[(DMValue)"Charlie"]));
            DMBuiltins.world_output((DMValue)"Lists test completed!");
            return __dot;
        }

    }

    public static class Program
    {
        public static int Main(string[] args)
        {
            DMWorld world = DMWorld.Instance;
            world.name = new DMValue("DM App");

            try
            {
                GlobalProcs.main();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Runtime Error: " + ex.Message);
                Console.WriteLine(ex.StackTrace);
                return 1;
            }

            return 0;
        }
    }
}
