// ==========================================================================
// Generated by DMToCSharp (DreamMaker to C# Transpiler)
// ==========================================================================
using System;
using System.Collections;
using System.Collections.Generic;
using DMToCSharp.Core;
using DMToCSharp.Runtime;

namespace DMCompiled
{
    public static class GlobalVars
    {
    }

    public static class GlobalProcs
    {
        public static DMValue evaluate_risk(DMValue threat_level = default(DMValue))
        {
            DMValue __dot = DMValue.Null;
            DMValue __sw_val = threat_level;
            if ((__sw_val == (DMValue)1))
            {
                return (DMValue)"Green: Normal";
            }else if ((__sw_val == (DMValue)2))
            {
                return (DMValue)"Blue: Caution";
            }else if ((__sw_val == (DMValue)3))
            {
                return (DMValue)"Red: Emergency";
            }else {
                {
                    return (DMValue)"Delta: Self Destruct";
                }
            }
            return __dot;
        }

        public static DMValue main()
        {
            DMValue __dot = DMValue.Null;
            DMBuiltins.world_output((DMValue)"=== DM Control Flow Test ===");
            DMValue power = (DMValue)85;
            if ((power > (DMValue)50)) 
            {
                DMBuiltins.world_output(DMValue.Format("Power grid is optimal: ", power, "%"));
            }
            else 
            {
                DMBuiltins.world_output((DMValue)"Power grid failure!");
            }
            DMValue count = (DMValue)0;
            for (DMValue i = (DMValue)1; i <= (DMValue)5; i += 1)
            {
                count += i;
            }
            DMBuiltins.world_output(DMValue.Format("Sum 1 to 5: ", count));
            DMValue w = (DMValue)3;
            while ((w > (DMValue)0)) 
            {
                DMBuiltins.world_output(DMValue.Format("Countdown: ", w));
                w--;
            }
            DMBuiltins.world_output(GlobalProcs.evaluate_risk((DMValue)2));
            DMBuiltins.world_output(GlobalProcs.evaluate_risk((DMValue)3));
            try
            {
                DMValue bad = (DMValue)0;
                DMBuiltins.world_output((DMValue)"Inside try block");
            }
            catch (Exception e_raw)
            {
                DMValue e = new DMValue(e_raw.Message);
                {
                    DMBuiltins.world_output(DMValue.Format("Caught error: ", e));
                }
            }
            DMBuiltins.world_output((DMValue)"Control flow test completed!");
            return __dot;
        }

    }

    public static class Program
    {
        public static int Main(string[] args)
        {
            DMWorld world = DMWorld.Instance;
            world.name = new DMValue("DM App");

            try
            {
                GlobalProcs.main();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Runtime Error: " + ex.Message);
                Console.WriteLine(ex.StackTrace);
                return 1;
            }

            return 0;
        }
    }
}
