// ==========================================================================
// Generated by DMToCSharp (DreamMaker to C# Transpiler)
// ==========================================================================
using System;
using System.Collections;
using System.Collections.Generic;
using DMToCSharp.Core;
using DMToCSharp.Runtime;

namespace DMCompiled
{
    public static class GlobalVars
    {
    }

    public static class GlobalProcs
    {
        public static DMValue main()
        {
            DMBuiltins.world_output((DMValue)"==================================================");
            DMBuiltins.world_output((DMValue)"    SPACE STATION 13 - COMBAT & INTERACTION DEMO  ");
            DMBuiltins.world_output((DMValue)"==================================================");
            DMValue security = (new DMObject().New());
            security.SetVar("name", (DMValue)"Officer Johnson");
            DMValue syndicate = (new DMObject().New());
            syndicate.SetVar("name", (DMValue)"Syndicate Operative");
            DMValue baton = (new DMObject().New());
            security.CallProc("equip", new DMValue[] { baton });
            DMBuiltins.world_output((DMValue)"--- Round 1 ---");
            security.CallProc("attack_target", new DMValue[] { syndicate });
            DMBuiltins.world_output((DMValue)"--- Round 2 ---");
            security.CallProc("attack_target", new DMValue[] { syndicate });
            DMBuiltins.world_output((DMValue)"--- Round 3 ---");
            syndicate.CallProc("attack_target", new DMValue[] { security });
            DMBuiltins.world_output((DMValue)"=== SS13 Simulation Completed Successfully ===");
            return DMValue.Null;
        }

    }

    public class DM_obj_item : DM_obj
    {
        public override DreamPath TypePath { get { return new DreamPath("/obj/item"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/obj"); } }

        public DM_obj_item()
        {
            name = new DMValue("item");
            name = (DMValue)"Generic Item";
        }

        public DMValue _ = (DMValue)1;

    }

    public class DM_obj_item_weapon : DM_obj_item
    {
        public override DreamPath TypePath { get { return new DreamPath("/obj/item/weapon"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/obj/item"); } }

        public DM_obj_item_weapon()
        {
            name = new DMValue("weapon");
            name = (DMValue)"Weapon";
        }

        public DMValue _ = (DMValue)10;

    }

    public class DM_obj_item_weapon_stun_baton : DM_obj_item_weapon
    {
        public override DreamPath TypePath { get { return new DreamPath("/obj/item/weapon/stun_baton"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/obj/item/weapon"); } }

        public DM_obj_item_weapon_stun_baton()
        {
            name = new DMValue("stun_baton");
            name = (DMValue)"Stun Baton";
        }

        public DMValue damage = (DMValue)25;
        public DMValue _ = (DMValue)5;

        public virtual DMValue attack(DMValue target = default(DMValue))
        {
            if ((this.GetVar("charges") <= (DMValue)0)) 
            {
                DMBuiltins.world_output(DMValue.Format(this.GetVar("name"), " has no charges left!"));
                return (DMValue)0;
            }
            this.SetVar("charges", (this.GetVar("charges") - (DMValue)1));
            DMBuiltins.world_output(DMValue.Format("*BZZZT* ", this.GetVar("name"), " zaps ", target.GetVar("name"), "! (", this.GetVar("charges"), " charges left)"));
            target.SetVar("health", (target.GetVar("health") - this.GetVar("damage")));
            return this.GetVar("damage");
            return DMValue.Null;
        }

    }

    public class DM_obj_item_weapon_laser_gun : DM_obj_item_weapon
    {
        public override DreamPath TypePath { get { return new DreamPath("/obj/item/weapon/laser_gun"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/obj/item/weapon"); } }

        public DM_obj_item_weapon_laser_gun()
        {
            name = new DMValue("laser_gun");
            name = (DMValue)"Laser Gun";
        }

        public DMValue damage = (DMValue)35;

    }

    public class DM_mob_living : DM_mob
    {
        public override DreamPath TypePath { get { return new DreamPath("/mob/living"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/mob"); } }

        public DM_mob_living()
        {
            name = new DMValue("living");
            name = (DMValue)"Living Being";
        }

        public DMValue _ = DMValue.Null;

        public virtual DMValue equip(DMValue new_item = default(DMValue))
        {
            this.SetVar("equipped_item", new_item);
            DMBuiltins.world_output(DMValue.Format(this.GetVar("name"), " equips ", new_item.GetVar("name"), "."));
            return DMValue.Null;
        }

        public virtual DMValue attack_target(DMValue target = default(DMValue))
        {
            if ((!this.GetVar("equipped_item"))) 
            {
                DMBuiltins.world_output(DMValue.Format(this.GetVar("name"), " punches ", target.GetVar("name"), " for 5 damage!"));
                target.SetVar("health", (target.GetVar("health") - (DMValue)5));
            }
            else 
                if (DMBuiltins.istype(this.GetVar("equipped_item"), new DMValue(new DreamPath("/obj/item/weapon/stun_baton")))) 
                {
                    DMValue baton = this.GetVar("equipped_item");
                    baton.CallProc("attack", new DMValue[] { target });
                }
                else 
                {
                    DMBuiltins.world_output(DMValue.Format(this.GetVar("name"), " attacks ", target.GetVar("name"), " with ", this.GetVar("equipped_item").GetVar("name"), "!"));
                    target.SetVar("health", (target.GetVar("health") - (DMValue)15));
                }
            DMBuiltins.world_output(DMValue.Format(target.GetVar("name"), " HP: ", target.GetVar("health"), "/", target.GetVar("max_health")));
            return DMValue.Null;
        }

    }

    public static class Program
    {
        public static int Main(string[] args)
        {
            DMWorld world = DMWorld.Instance;
            world.name = new DMValue("DM App");

            try
            {
                GlobalProcs.main();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Runtime Error: " + ex.Message);
                Console.WriteLine(ex.StackTrace);
                return 1;
            }

            return 0;
        }
    }
}
