// ==========================================================================
// Generated by DMToCSharp (DreamMaker to C# Transpiler)
// ==========================================================================
using System;
using System.Collections;
using System.Collections.Generic;
using DMToCSharp.Core;
using DMToCSharp.Runtime;

namespace DMCompiled
{
    public static class GlobalVars
    {
    }

    public static class GlobalProcs
    {
        public static DMValue main()
        {
            DMValue __dot = DMValue.Null;
            DMBuiltins.world_output((DMValue)"=== SS13 DMM Map Loading Test ===");
            DMValue map_data = (DMValue)"\"aaa\" = (/turf/open/floor{icon_state = \"floor\"; density = 0}, /area/hallway)\n\"aab\" = (/turf/closed/wall{icon_state = \"wall\"; density = 1}, /area/hallway)\n\"aac\" = (/obj/machinery/door/airlock, /turf/open/floor, /area/hallway)\n\n(1, 1, 1) = {\"\naabaaa\naacaaa\n\"}\n";
            DMValue success = DMBuiltins.load_map(map_data);
            DMBuiltins.world_output(DMValue.Format("DMM Map load success: ", success));
            DMValue t1 = DMBuiltins.locate((DMValue)1, (DMValue)1, (DMValue)1);
            DMValue t2 = DMBuiltins.locate((DMValue)2, (DMValue)1, (DMValue)1);
            DMBuiltins.world_output(DMValue.Format("Turf (1,1,1) is: ", t1.GetVar("name"), ", density: ", t1.GetVar("density")));
            DMBuiltins.world_output(DMValue.Format("Turf (2,1,1) is: ", t2.GetVar("name"), ", density: ", t2.GetVar("density")));
            DMBuiltins.world_output((DMValue)"DMM Map loading test completed successfully!");
            return __dot;
        }

    }

    public static class Program
    {
        public static int Main(string[] args)
        {
            DMWorld world = DMWorld.Instance;
            world.name = new DMValue("DM App");

            try
            {
                GlobalProcs.main();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Runtime Error: " + ex.Message);
                Console.WriteLine(ex.StackTrace);
                return 1;
            }

            return 0;
        }
    }
}
