// ==========================================================================
// Generated by DMToCSharp (DreamMaker to C# Transpiler)
// ==========================================================================
using System;
using System.Collections;
using System.Collections.Generic;
using DMToCSharp.Core;
using DMToCSharp.Runtime;

namespace DMCompiled
{
    public static class GlobalVars
    {
    }

    public static class GlobalProcs
    {
        public static DMValue main()
        {
            DMValue __dot = DMValue.Null;
            DMBuiltins.world_output((DMValue)"=== SS13 Master Controller Subsystem Test ===");
            DMValue SSair = (new DMValue(new DMObject().InitAndNew()));
            DMValue SSmachines = (new DMValue(new DMObject().InitAndNew()));
            DMBuiltins.world_output((DMValue)"Initializing subsystems...");
            SSair.CallProc("fire", new DMValue[] {  });
            SSmachines.CallProc("fire", new DMValue[] {  });
            DMBuiltins.world_output((DMValue)"Round 2 Ticking...");
            SSair.CallProc("fire", new DMValue[] {  });
            SSmachines.CallProc("fire", new DMValue[] {  });
            DMBuiltins.world_output((DMValue)"Master Controller test completed successfully!");
            return __dot;
        }

    }

    public class DM_datum_controller : DM_datum
    {
        public override DreamPath TypePath { get { return new DreamPath("/datum/controller"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/datum"); } }

        public DM_datum_controller()
        {
            name = new DMValue("controller");
        }


    }

    public class DM_datum_controller_subsystem : DM_datum_controller
    {
        public override DreamPath TypePath { get { return new DreamPath("/datum/controller/subsystem"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/datum/controller"); } }

        public DM_datum_controller_subsystem()
        {
            name = new DMValue("subsystem");
        }


    }

    public class DM_datum_controller_subsystem_air : DM_datum_controller_subsystem
    {
        public override DreamPath TypePath { get { return new DreamPath("/datum/controller/subsystem/air"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/datum/controller/subsystem"); } }

        public DM_datum_controller_subsystem_air()
        {
            name = new DMValue("air");
            name = (DMValue)"Atmospherics";
        }

        public DMValue _ = (DMValue)101.3;

        public virtual DMValue fire()
        {
            DMValue __dot = DMValue.Null;
            this.SetVar("pressure", (this.GetVar("pressure") - (DMValue)0.1));
            DMBuiltins.world_output(DMValue.Format(this.GetVar("name"), " tick: pressure at ", this.GetVar("pressure"), " kPa"));
            return (DMValue)1;
            return __dot;
        }

    }

    public class DM_datum_controller_subsystem_machinery : DM_datum_controller_subsystem
    {
        public override DreamPath TypePath { get { return new DreamPath("/datum/controller/subsystem/machinery"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/datum/controller/subsystem"); } }

        public DM_datum_controller_subsystem_machinery()
        {
            name = new DMValue("machinery");
            name = (DMValue)"Machinery";
        }

        public DMValue _ = (DMValue)500;

        public virtual DMValue fire()
        {
            DMValue __dot = DMValue.Null;
            this.SetVar("power_draw", (this.GetVar("power_draw") + (DMValue)25));
            DMBuiltins.world_output(DMValue.Format(this.GetVar("name"), " tick: total power load ", this.GetVar("power_draw"), " kW"));
            return (DMValue)1;
            return __dot;
        }

    }

    public static class Program
    {
        public static int Main(string[] args)
        {
            DMWorld world = DMWorld.Instance;
            world.name = new DMValue("DM App");

            try
            {
                GlobalProcs.main();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Runtime Error: " + ex.Message);
                Console.WriteLine(ex.StackTrace);
                return 1;
            }

            return 0;
        }
    }
}
