// ==========================================================================
// Generated by DMToCSharp (DreamMaker to C# Transpiler)
// ==========================================================================
using System;
using System.Collections;
using System.Collections.Generic;
using DMToCSharp.Core;
using DMToCSharp.Runtime;

namespace DMCompiled
{
    public static class GlobalVars
    {
    }

    public static class GlobalProcs
    {
        public static DMValue main()
        {
            DMValue __dot = DMValue.Null;
            DMBuiltins.world_output((DMValue)"=== SS13 Rust-g FFI & Spatial Queries Test ===");
            DMValue hash_res = DMBuiltins.call_ext((DMValue)"rust_g.dll", (DMValue)"rustg_hash_string", (DMValue)"sha256", (DMValue)"SpaceStation13");
            DMBuiltins.world_output(DMValue.Format("Rust-g SHA256 of 'SpaceStation13': ", hash_res));
            DMValue noise_val = DMBuiltins.call_ext((DMValue)"rust_g.dll", (DMValue)"rustg_noise_2d", (DMValue)"12.5", (DMValue)"45.8");
            DMBuiltins.world_output(DMValue.Format("Rust-g Noise at (12.5, 45.8): ", noise_val));
            DMValue is_valid = DMBuiltins.call_ext((DMValue)"rust_g.dll", (DMValue)"rustg_json_is_valid", (DMValue)"{\"station\": \"SpaceStation13\", \"id\": 13}");
            DMBuiltins.world_output(DMValue.Format("Rust-g JSON is valid: ", is_valid));
            DMValue mob1 = (new DMValue(new DM_mob().InitAndNew()));
            mob1.SetVar("x", (DMValue)10);
            mob1.SetVar("y", (DMValue)10);
            DMValue mob2 = (new DMValue(new DM_mob().InitAndNew()));
            mob2.SetVar("x", (DMValue)14);
            mob2.SetVar("y", (DMValue)13);
            DMValue dist = DMBuiltins.get_dist(mob1, mob2);
            DMBuiltins.world_output(DMValue.Format("Distance between (10,10) and (14,13): ", dist));
            DMValue dir = DMBuiltins.get_dir(mob1, mob2);
            DMBuiltins.world_output(DMValue.Format("Direction from mob1 to mob2: ", dir));
            DMBuiltins.world_output((DMValue)"Rust-g & Spatial test completed successfully!");
            return __dot;
        }

    }

    public static class Program
    {
        public static int Main(string[] args)
        {
            DMWorld world = DMWorld.Instance;
            world.name = new DMValue("DM App");

            try
            {
                GlobalProcs.main();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Runtime Error: " + ex.Message);
                Console.WriteLine(ex.StackTrace);
                return 1;
            }

            return 0;
        }
    }
}
