// ==========================================================================
// Generated by DMToCSharp (DreamMaker to C# Transpiler)
// ==========================================================================
using System;
using System.Collections;
using System.Collections.Generic;
using DMToCSharp.Core;
using DMToCSharp.Runtime;

namespace DMCompiled
{
    public static class GlobalVars
    {
    }

    public static class GlobalProcs
    {
        public static DMValue main()
        {
            DMValue __dot = DMValue.Null;
            DMBuiltins.world_output((DMValue)"=== SS13 Batch Project & Network Test ===");
            DMValue main_net = (new DMValue(new DMObject().InitAndNew()));
            DMValue sec_net = (new DMValue(new DMObject().InitAndNew()));
            main_net.CallProc("send_packet", new DMValue[] { (DMValue)"Captain", (DMValue)"All", (DMValue)"Welcome to Space Station 13!" });
            sec_net.CallProc("send_packet", new DMValue[] { (DMValue)"Head of Security", (DMValue)"Warden", (DMValue)"Brig is secure." });
            DMBuiltins.world_output(DMValue.Format("Main net packets: ", main_net.GetVar("packets_processed")));
            DMBuiltins.world_output(DMValue.Format("Sec net packets: ", sec_net.GetVar("packets_processed")));
            DMBuiltins.world_output((DMValue)"Batch Project Compilation test completed successfully!");
            return __dot;
        }

    }

    public class DM_datum_station_network : DM_datum
    {
        public override DreamPath TypePath { get { return new DreamPath("/datum/station_network"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/datum"); } }

        public DM_datum_station_network()
        {
            name = new DMValue("station_network");
        }

        public DMValue _ = (DMValue)0;

        public virtual DMValue send_packet(DMValue sender = default(DMValue), DMValue recipient = default(DMValue), DMValue data = default(DMValue))
        {
            DMValue __dot = DMValue.Null;
            this.SetVar("packets_processed", (this.GetVar("packets_processed") + (DMValue)1));
            DMBuiltins.world_output(DMValue.Format("Network ", this.GetVar("network_name"), ": '", sender, "' -> '", recipient, "': ", data));
            return (DMValue)1;
            return __dot;
        }

    }

    public class DM_datum_station_network_security : DM_datum_station_network
    {
        public override DreamPath TypePath { get { return new DreamPath("/datum/station_network/security"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/datum/station_network"); } }

        public DM_datum_station_network_security()
        {
            name = new DMValue("security");
        }

        public DMValue network_name = (DMValue)"Security Encrypted Channel";

    }

    public static class Program
    {
        public static int Main(string[] args)
        {
            DMWorld world = DMWorld.Instance;
            world.name = new DMValue("DM App");

            try
            {
                GlobalProcs.main();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Runtime Error: " + ex.Message);
                Console.WriteLine(ex.StackTrace);
                return 1;
            }

            return 0;
        }
    }
}
