// ==========================================================================
// Generated by DMToCSharp (DreamMaker to C# Transpiler)
// ==========================================================================
using System;
using System.Collections;
using System.Collections.Generic;
using DMToCSharp.Core;
using DMToCSharp.Runtime;

namespace DMCompiled
{
    public static class GlobalVars
    {
    }

    public static class GlobalProcs
    {
        public static DMValue main()
        {
            DMValue __dot = DMValue.Null;
            DMBuiltins.world_output((DMValue)"=== SS13 Chemistry & Health Simulation Test ===");
            DMValue beaker = (new DMValue(new DMObject().InitAndNew()));
            beaker.CallProc("add_reagent", new DMValue[] { (DMValue)"welding_fuel", (DMValue)10 });
            beaker.CallProc("add_reagent", new DMValue[] { (DMValue)"oxygen", (DMValue)10 });
            DMBuiltins.world_output(DMValue.Format("Beaker Volume: ", beaker.GetVar("volume"), "u, Temp: ", beaker.GetVar("temperature"), "K"));
            DMValue patient = (new DMValue(new DMObject().InitAndNew()));
            patient.CallProc("take_damage", new DMValue[] { (DMValue)"brute", (DMValue)25 });
            patient.CallProc("take_damage", new DMValue[] { (DMValue)"burn", (DMValue)15 });
            DMBuiltins.world_output(DMValue.Format("Patient Health after damage: ", patient.GetVar("health"), "/100 HP (Brute: ", patient.GetVar("brute"), ", Burn: ", patient.GetVar("burn"), ")"));
            patient.CallProc("heal_damage", new DMValue[] { (DMValue)20 });
            DMBuiltins.world_output(DMValue.Format("Patient Health after medical treatment: ", patient.GetVar("health"), "/100 HP"));
            DMBuiltins.world_output((DMValue)"Chemistry & Health test completed successfully!");
            return __dot;
        }

    }

    public class DM_datum_reagent_beaker : DM_datum
    {
        public override DreamPath TypePath { get { return new DreamPath("/datum/reagent_beaker"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/datum"); } }

        public DM_datum_reagent_beaker()
        {
            name = new DMValue("reagent_beaker");
        }

        public DMValue _ = DMBuiltins.list_init(new object[] {  });

        public virtual DMValue add_reagent(DMValue id = default(DMValue), DMValue amount = default(DMValue))
        {
            DMValue __dot = DMValue.Null;
            if (((this.GetVar("volume") + amount) > this.GetVar("max_volume"))) 
            {
                amount = (this.GetVar("max_volume") - this.GetVar("volume"));
            }
            this.SetVar("volume", (this.GetVar("volume") + amount));
            DMValue cur = this.GetVar("reagents")[id];
            if ((!cur)) 
            {
                cur = (DMValue)0;
            }
            DMBuiltins.set_index(this.GetVar("reagents"), id, (cur + amount));
            this.check_reactions();
            return amount;
            return __dot;
        }

        public virtual DMValue check_reactions()
        {
            DMValue __dot = DMValue.Null;
            if ((this.GetVar("reagents")[(DMValue)"welding_fuel"] && this.GetVar("reagents")[(DMValue)"oxygen"])) 
            {
                DMValue fuel = this.GetVar("reagents")[(DMValue)"welding_fuel"];
                DMValue oxy = this.GetVar("reagents")[(DMValue)"oxygen"];
                DMValue react = fuel;
                if ((oxy < fuel)) 
                {
                    react = oxy;
                }
                DMBuiltins.set_index(this.GetVar("reagents"), (DMValue)"welding_fuel", (this.GetVar("reagents")[(DMValue)"welding_fuel"] - react));
                DMBuiltins.set_index(this.GetVar("reagents"), (DMValue)"oxygen", (this.GetVar("reagents")[(DMValue)"oxygen"] - react));
                DMValue carb = this.GetVar("reagents")[(DMValue)"carbon"];
                if ((!carb)) 
                {
                    carb = (DMValue)0;
                }
                DMBuiltins.set_index(this.GetVar("reagents"), (DMValue)"carbon", (carb + (react * (DMValue)0.8)));
                this.SetVar("temperature", (this.GetVar("temperature") + (react * (DMValue)15)));
                DMBuiltins.world_output(DMValue.Format("Chemical Reaction: Fuel + Oxygen -> Carbon Ash (Temp: ", this.GetVar("temperature"), "K)"));
            }
            return __dot;
        }

    }

    public class DM_datum_human_medical : DM_datum
    {
        public override DreamPath TypePath { get { return new DreamPath("/datum/human_medical"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/datum"); } }

        public DM_datum_human_medical()
        {
            name = new DMValue("human_medical");
        }

        public DMValue _ = (DMValue)560;

        public virtual DMValue take_damage(DMValue d_type = default(DMValue), DMValue amount = default(DMValue))
        {
            DMValue __dot = DMValue.Null;
            if ((d_type == (DMValue)"brute")) 
            {
                this.SetVar("brute", (this.GetVar("brute") + amount));
            }
            else 
                if ((d_type == (DMValue)"burn")) 
                {
                    this.SetVar("burn", (this.GetVar("burn") + amount));
                }
                else 
                    if ((d_type == (DMValue)"toxin")) 
                    {
                        this.SetVar("toxin", (this.GetVar("toxin") + amount));
                    }
            this.SetVar("health", ((DMValue)100 - ((this.GetVar("brute") + this.GetVar("burn")) + this.GetVar("toxin"))));
            return __dot;
        }

        public virtual DMValue heal_damage(DMValue amount = default(DMValue))
        {
            DMValue __dot = DMValue.Null;
            if ((this.GetVar("brute") > amount)) 
            {
                this.SetVar("brute", (this.GetVar("brute") - amount));
            }
            else 
            {
                this.SetVar("brute", (DMValue)0);
            }
            if ((this.GetVar("burn") > amount)) 
            {
                this.SetVar("burn", (this.GetVar("burn") - amount));
            }
            else 
            {
                this.SetVar("burn", (DMValue)0);
            }
            this.SetVar("health", ((DMValue)100 - ((this.GetVar("brute") + this.GetVar("burn")) + this.GetVar("toxin"))));
            return __dot;
        }

    }

    public static class Program
    {
        public static int Main(string[] args)
        {
            DMWorld world = DMWorld.Instance;
            world.name = new DMValue("DM App");

            try
            {
                GlobalProcs.main();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Runtime Error: " + ex.Message);
                Console.WriteLine(ex.StackTrace);
                return 1;
            }

            return 0;
        }
    }
}
