// ==========================================================================
// Generated by DMToCSharp (DreamMaker to C# Transpiler)
// ==========================================================================
using System;
using System.Collections;
using System.Collections.Generic;
using DMToCSharp.Core;
using DMToCSharp.Runtime;

namespace DMCompiled
{
    public static class GlobalVars
    {
    }

    public static class GlobalProcs
    {
        public static DMValue main()
        {
            DMValue __dot = DMValue.Null;
            DMBuiltins.world_output((DMValue)"=== SS13 Inventory & Tool Interactions Test ===");
            DMValue inv = (new DMValue(new DMObject().InitAndNew()));
            DMValue C = (new DMValue(new DMObject().InitAndNew()));
            DMValue S = (new DMValue(new DMObject().InitAndNew()));
            inv.CallProc("equip_right", new DMValue[] { C });
            inv.CallProc("equip_belt", new DMValue[] { S });
            DMValue door = (new DMValue(new DMObject().InitAndNew()));
            door.CallProc("use_tool", new DMValue[] { C });
            door.CallProc("use_tool", new DMValue[] { S });
            DMBuiltins.world_output(DMValue.Format("Door state: Opened=", door.GetVar("opened"), ", Panel=", door.GetVar("panel_open")));
            DMBuiltins.world_output((DMValue)"Inventory & Tool test completed successfully!");
            return __dot;
        }

    }

    public class DM_obj_item : DM_obj
    {
        public override DreamPath TypePath { get { return new DreamPath("/obj/item"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/obj"); } }

        public DM_obj_item()
        {
            name = new DMValue("item");
        }

        public DMValue _ = (DMValue)1;

    }

    public class DM_obj_item_tool : DM_obj_item
    {
        public override DreamPath TypePath { get { return new DreamPath("/obj/item/tool"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/obj/item"); } }

        public DM_obj_item_tool()
        {
            name = new DMValue("tool");
        }

        public DMValue _ = (DMValue)"generic";

    }

    public class DM_obj_item_tool_crowbar : DM_obj_item_tool
    {
        public override DreamPath TypePath { get { return new DreamPath("/obj/item/tool/crowbar"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/obj/item/tool"); } }

        public DM_obj_item_tool_crowbar()
        {
            name = new DMValue("crowbar");
            name = (DMValue)"mechanical crowbar";
        }

        public DMValue tool_type = (DMValue)"crowbar";

    }

    public class DM_obj_item_tool_screwdriver : DM_obj_item_tool
    {
        public override DreamPath TypePath { get { return new DreamPath("/obj/item/tool/screwdriver"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/obj/item/tool"); } }

        public DM_obj_item_tool_screwdriver()
        {
            name = new DMValue("screwdriver");
            name = (DMValue)"screwdriver";
        }

        public DMValue tool_type = (DMValue)"screwdriver";

    }

    public class DM_datum_inventory : DM_datum
    {
        public override DreamPath TypePath { get { return new DreamPath("/datum/inventory"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/datum"); } }

        public DM_datum_inventory()
        {
            name = new DMValue("inventory");
        }

        public DMValue _ = DMValue.Null;

        public virtual DMValue equip_right(DMValue I = default(DMValue))
        {
            DMValue __dot = DMValue.Null;
            this.SetVar("right_hand", I);
            DMBuiltins.world_output(DMValue.Format("Equipped ", I.GetVar("name"), " to Right Hand"));
            return (DMValue)1;
            return __dot;
        }

        public virtual DMValue equip_belt(DMValue I = default(DMValue))
        {
            DMValue __dot = DMValue.Null;
            this.SetVar("belt", I);
            DMBuiltins.world_output(DMValue.Format("Equipped ", I.GetVar("name"), " to Belt"));
            return (DMValue)1;
            return __dot;
        }

    }

    public class DM_obj_machinery : DM_obj
    {
        public override DreamPath TypePath { get { return new DreamPath("/obj/machinery"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/obj"); } }

        public DM_obj_machinery()
        {
            name = new DMValue("machinery");
        }


    }

    public class DM_obj_machinery_door : DM_obj_machinery
    {
        public override DreamPath TypePath { get { return new DreamPath("/obj/machinery/door"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/obj/machinery"); } }

        public DM_obj_machinery_door()
        {
            name = new DMValue("door");
        }


    }

    public class DM_obj_machinery_door_airlock : DM_obj_machinery_door
    {
        public override DreamPath TypePath { get { return new DreamPath("/obj/machinery/door/airlock"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/obj/machinery/door"); } }

        public DM_obj_machinery_door_airlock()
        {
            name = new DMValue("airlock");
            name = (DMValue)"secure airlock";
        }

        public DMValue _ = (DMValue)0;

        public virtual DMValue use_tool(DMValue T = default(DMValue))
        {
            DMValue __dot = DMValue.Null;
            if ((T.GetVar("tool_type") == (DMValue)"crowbar")) 
            {
                if ((!this.GetVar("bolted"))) 
                {
                    if (this.GetVar("opened")) 
                    {
                        this.SetVar("opened", (DMValue)0);
                    }
                    else 
                    {
                        this.SetVar("opened", (DMValue)1);
                    }
                    DMBuiltins.world_output(DMValue.Format("Pried ", this.GetVar("name"), " state ", this.GetVar("opened"), " with crowbar."));
                    return (DMValue)1;
                }
            }
            else 
                if ((T.GetVar("tool_type") == (DMValue)"screwdriver")) 
                {
                    if (this.GetVar("panel_open")) 
                    {
                        this.SetVar("panel_open", (DMValue)0);
                    }
                    else 
                    {
                        this.SetVar("panel_open", (DMValue)1);
                    }
                    DMBuiltins.world_output(DMValue.Format("Maintenance panel on ", this.GetVar("name"), " state is ", this.GetVar("panel_open"), "."));
                    return (DMValue)1;
                }
            return (DMValue)0;
            return __dot;
        }

    }

    public static class Program
    {
        public static int Main(string[] args)
        {
            DMWorld world = DMWorld.Instance;
            world.name = new DMValue("DM App");

            try
            {
                GlobalProcs.main();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Runtime Error: " + ex.Message);
                Console.WriteLine(ex.StackTrace);
                return 1;
            }

            return 0;
        }
    }
}
