// ==========================================================================
// Generated by DMToCSharp (DreamMaker to C# Transpiler)
// ==========================================================================
using System;
using System.Collections;
using System.Collections.Generic;
using DMToCSharp.Core;
using DMToCSharp.Runtime;

namespace DMCompiled
{
    public static class GlobalVars
    {
    }

    public static class GlobalProcs
    {
        public static DMValue main()
        {
            DMValue __dot = DMValue.Null;
            DMBuiltins.world_output((DMValue)"=== SS13 Telecomms & Radio Subsystem Test ===");
            DMValue common_freq = (new DMValue(new DMObject().InitAndNew()));
            DMValue sec_freq = (new DMValue(new DMObject().InitAndNew()));
            sec_freq.SetVar("frequency", (DMValue)135.9);
            sec_freq.SetVar("channel_name", (DMValue)"Security");
            common_freq.CallProc("broadcast", new DMValue[] { (DMValue)"Captain", (DMValue)"Command", (DMValue)"All crew report to bridge." });
            sec_freq.CallProc("broadcast", new DMValue[] { (DMValue)"Warden", (DMValue)"Security", (DMValue)"Armory is on lockdown." });
            DMBuiltins.world_output(DMValue.Format("Common transmissions count: ", common_freq.GetVar("transmissions").GetVar("len")));
            DMBuiltins.world_output(DMValue.Format("Security transmissions count: ", sec_freq.GetVar("transmissions").GetVar("len")));
            DMBuiltins.world_output((DMValue)"Telecomms & Radio test completed successfully!");
            return __dot;
        }

    }

    public class DM_datum_radio_frequency : DM_datum
    {
        public override DreamPath TypePath { get { return new DreamPath("/datum/radio_frequency"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/datum"); } }

        public DM_datum_radio_frequency()
        {
            name = new DMValue("radio_frequency");
        }

        public DMValue _ = DMBuiltins.list_init(new object[] {  });

        public virtual DMValue broadcast(DMValue sender = default(DMValue), DMValue job = default(DMValue), DMValue message = default(DMValue))
        {
            DMValue __dot = DMValue.Null;
            DMValue entry = DMValue.Format(DMValue.Null, " ", sender, " (", job, "): \"", message, "\"");
            this.GetVar("transmissions").CallProc("Add", new DMValue[] { entry });
            DMBuiltins.world_output(entry);
            return (DMValue)1;
            return __dot;
        }

    }

    public static class Program
    {
        public static int Main(string[] args)
        {
            DMWorld world = DMWorld.Instance;
            world.name = new DMValue("DM App");

            try
            {
                GlobalProcs.main();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Runtime Error: " + ex.Message);
                Console.WriteLine(ex.StackTrace);
                return 1;
            }

            return 0;
        }
    }
}
