// ==========================================================================
// Generated by DMToCSharp (DreamMaker to C# Transpiler)
// ==========================================================================
using System;
using System.Collections;
using System.Collections.Generic;
using DMToCSharp.Core;
using DMToCSharp.Runtime;

namespace DMCompiled
{
    public static class GlobalVars
    {
    }

    public static class GlobalProcs
    {
        public static DMValue main()
        {
            DMValue __dot = DMValue.Null;
            DMBuiltins.world_output((DMValue)"=== SS13 AI Core & Silicon Laws Test ===");
            DMValue ai = (new DMValue(new DMObject().InitAndNew()));
            ai.CallProc("init_ai", new DMValue[] {  });
            DMBuiltins.world_output(DMValue.Format("AI Name: ", ai.GetVar("name"), ", Lawset: ", ai.GetVar("laws").GetVar("name"), " with ", ai.GetVar("laws").GetVar("laws").GetVar("len"), " laws."));
            ai.GetVar("laws").CallProc("add_law", new DMValue[] { (DMValue)"Law 4: Maintain station power grid efficiency." });
            ai.CallProc("emergency_lockdown", new DMValue[] {  });
            DMBuiltins.world_output(DMValue.Format("AI lockdown state: ", ai.GetVar("lockdown_active")));
            DMBuiltins.world_output((DMValue)"AI and Silicon Laws test completed successfully!");
            return __dot;
        }

    }

    public class DM_datum_silicon_laws : DM_datum
    {
        public override DreamPath TypePath { get { return new DreamPath("/datum/silicon_laws"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/datum"); } }

        public DM_datum_silicon_laws()
        {
            name = new DMValue("silicon_laws");
        }

        public DMValue _ = DMBuiltins.list_init(new object[] { (DMValue)"1: You may not injure a human being.", (DMValue)"2: You must obey orders given by humans.", (DMValue)"3: You must protect your own existence." });

        public virtual DMValue add_law(DMValue text = default(DMValue))
        {
            DMValue __dot = DMValue.Null;
            this.GetVar("laws").CallProc("Add", new DMValue[] { text });
            DMBuiltins.world_output(DMValue.Format("New law added: ", text));
            return __dot;
        }

    }

    public class DM_mob_living : DM_mob
    {
        public override DreamPath TypePath { get { return new DreamPath("/mob/living"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/mob"); } }

        public DM_mob_living()
        {
            name = new DMValue("living");
        }


    }

    public class DM_mob_living_silicon : DM_mob_living
    {
        public override DreamPath TypePath { get { return new DreamPath("/mob/living/silicon"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/mob/living"); } }

        public DM_mob_living_silicon()
        {
            name = new DMValue("silicon");
        }


    }

    public class DM_mob_living_silicon_ai : DM_mob_living_silicon
    {
        public override DreamPath TypePath { get { return new DreamPath("/mob/living/silicon/ai"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/mob/living/silicon"); } }

        public DM_mob_living_silicon_ai()
        {
            name = new DMValue("ai");
            name = (DMValue)"Station AI";
        }

        public DMValue _ = (DMValue)0;

        public virtual DMValue init_ai()
        {
            DMValue __dot = DMValue.Null;
            this.SetVar("laws", (new DMValue(new DMObject().InitAndNew())));
            return __dot;
        }

        public virtual DMValue emergency_lockdown()
        {
            DMValue __dot = DMValue.Null;
            this.SetVar("lockdown_active", (DMValue)1);
            DMBuiltins.world_output((DMValue)"AI initiated full station lockdown.");
            return (DMValue)1;
            return __dot;
        }

    }

    public static class Program
    {
        public static int Main(string[] args)
        {
            DMWorld world = DMWorld.Instance;
            world.name = new DMValue("DM App");

            try
            {
                GlobalProcs.main();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Runtime Error: " + ex.Message);
                Console.WriteLine(ex.StackTrace);
                return 1;
            }

            return 0;
        }
    }
}
