// ==========================================================================
// Generated by DMToCSharp (DreamMaker to C# Transpiler)
// ==========================================================================
using System;
using System.Collections;
using System.Collections.Generic;
using DMToCSharp.Core;
using DMToCSharp.Runtime;

namespace DMCompiled
{
    public static class GlobalVars
    {
    }

    public static class GlobalProcs
    {
        public static DMValue calculate_wall_autotile(DMValue n = default(DMValue), DMValue s = default(DMValue), DMValue e = default(DMValue), DMValue w = default(DMValue))
        {
            DMValue __dot = DMValue.Null;
            DMValue mask = (DMValue)0;
            if (n) 
            {
                mask += (DMValue)1;
            }
            if (s) 
            {
                mask += (DMValue)2;
            }
            if (e) 
            {
                mask += (DMValue)4;
            }
            if (w) 
            {
                mask += (DMValue)8;
            }
            return mask;
            return __dot;
        }

        public static DMValue main()
        {
            DMValue __dot = DMValue.Null;
            DMBuiltins.world_output((DMValue)"=== SS13 DMI Metadata & Autotiling Test ===");
            DMValue dmi = (new DMValue(new DMObject().InitAndNew()));
            DMBuiltins.world_output(DMValue.Format("DMI Dimensions: ", dmi.GetVar("width"), "x", dmi.GetVar("height"), ", Version: ", dmi.GetVar("version"), ", States: ", dmi.CallProc("get_state_count", new DMValue[] {  })));
            DMValue mask_ne = GlobalProcs.calculate_wall_autotile((DMValue)1, (DMValue)0, (DMValue)1, (DMValue)0);
            DMValue mask_full = GlobalProcs.calculate_wall_autotile((DMValue)1, (DMValue)1, (DMValue)1, (DMValue)1);
            DMBuiltins.world_output(DMValue.Format("Autotile Corner (N+E): ", mask_ne));
            DMBuiltins.world_output(DMValue.Format("Autotile Cross (All): ", mask_full));
            DMBuiltins.world_output((DMValue)"DMI and Graphics test completed successfully!");
            return __dot;
        }

    }

    public class DM_datum_dmi_metadata : DM_datum
    {
        public override DreamPath TypePath { get { return new DreamPath("/datum/dmi_metadata"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/datum"); } }

        public DM_datum_dmi_metadata()
        {
            name = new DMValue("dmi_metadata");
        }

        public DMValue _ = DMBuiltins.list_init(new object[] { (DMValue)"floor", (DMValue)"wall", (DMValue)"door_open", (DMValue)"door_closed" });

        public virtual DMValue get_state_count()
        {
            DMValue __dot = DMValue.Null;
            return this.GetVar("states").GetVar("len");
            return __dot;
        }

    }

    public static class Program
    {
        public static int Main(string[] args)
        {
            DMWorld world = DMWorld.Instance;
            world.name = new DMValue("DM App");

            try
            {
                GlobalProcs.main();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Runtime Error: " + ex.Message);
                Console.WriteLine(ex.StackTrace);
                return 1;
            }

            return 0;
        }
    }
}
