// ==========================================================================
// Generated by DMToCSharp (DreamMaker to C# Transpiler)
// ==========================================================================
using System;
using System.Collections;
using System.Collections.Generic;
using DMToCSharp.Core;
using DMToCSharp.Runtime;

namespace DMCompiled
{
    public static class GlobalVars
    {
    }

    public static class GlobalProcs
    {
        public static DMValue main()
        {
            DMValue __dot = DMValue.Null;
            DMBuiltins.world_output((DMValue)"=== SS13 Dynamic Lighting & Audio Simulation Test ===");
            DMValue light = (new DMValue(new DMObject().InitAndNew()));
            DMValue lum_center = light.CallProc("calculate_lum", new DMValue[] { (DMValue)0 });
            DMValue lum_edge = light.CallProc("calculate_lum", new DMValue[] { (DMValue)3 });
            DMBuiltins.world_output(DMValue.Format("Center Luminosity: ", lum_center, ", Edge Luminosity: ", lum_edge));
            DMValue emitter = (new DMValue(new DMObject().InitAndNew()));
            DMValue vol_near = emitter.CallProc("get_perceived_volume", new DMValue[] { (DMValue)2 });
            DMValue vol_far = emitter.CallProc("get_perceived_volume", new DMValue[] { (DMValue)8 });
            DMBuiltins.world_output(DMValue.Format("Audio Near Volume: ", vol_near, ", Audio Far Volume: ", vol_far));
            DMBuiltins.world_output((DMValue)"Lighting & Audio test completed successfully!");
            return __dot;
        }

    }

    public class DM_datum_light_source : DM_datum
    {
        public override DreamPath TypePath { get { return new DreamPath("/datum/light_source"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/datum"); } }

        public DM_datum_light_source()
        {
            name = new DMValue("light_source");
        }

        public DMValue _ = (DMValue)"#ffffff";

        public virtual DMValue calculate_lum(DMValue dist = default(DMValue))
        {
            DMValue __dot = DMValue.Null;
            if ((dist > this.GetVar("range"))) 
            {
                return (DMValue)0;
            }
            DMValue falloff = ((DMValue)1 - (dist / (this.GetVar("range") + (DMValue)1)));
            return (falloff * this.GetVar("power"));
            return __dot;
        }

    }

    public class DM_datum_sound_emitter : DM_datum
    {
        public override DreamPath TypePath { get { return new DreamPath("/datum/sound_emitter"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/datum"); } }

        public DM_datum_sound_emitter()
        {
            name = new DMValue("sound_emitter");
        }

        public DMValue _ = (DMValue)100;

        public virtual DMValue get_perceived_volume(DMValue dist = default(DMValue))
        {
            DMValue __dot = DMValue.Null;
            if ((dist > this.GetVar("max_dist"))) 
            {
                return (DMValue)0;
            }
            DMValue attenuation = ((DMValue)1 - (dist / this.GetVar("max_dist")));
            return ((this.GetVar("volume") / (DMValue)100) * attenuation);
            return __dot;
        }

    }

    public static class Program
    {
        public static int Main(string[] args)
        {
            DMWorld world = DMWorld.Instance;
            world.name = new DMValue("DM App");

            try
            {
                GlobalProcs.main();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Runtime Error: " + ex.Message);
                Console.WriteLine(ex.StackTrace);
                return 1;
            }

            return 0;
        }
    }
}
