// ==========================================================================
// Generated by DMToCSharp (DreamMaker to C# Transpiler)
// ==========================================================================
using System;
using System.Collections;
using System.Collections.Generic;
using DMToCSharp.Core;
using DMToCSharp.Runtime;

namespace DMCompiled
{
    public static class GlobalVars
    {
    }

    public static class GlobalProcs
    {
        public static DMValue main()
        {
            DMValue __dot = DMValue.Null;
            DMBuiltins.world_output((DMValue)"=== SS13 Game Modes & Database Test ===");
            DMValue traitor = (new DMValue(new DMObject().InitAndNew()));
            traitor.CallProc("add_objective", new DMValue[] { (DMValue)"Infiltrate Command" });
            traitor.CallProc("add_objective", new DMValue[] { (DMValue)"Steal Nuclear Disk" });
            DMBuiltins.world_output(DMValue.Format("Antag: ", traitor.GetVar("role_name"), ", TC: ", traitor.GetVar("telecrystals"), ", Objectives: ", traitor.GetVar("objectives").GetVar("len")));
            DMValue profile = (new DMValue(new DMObject().InitAndNew()));
            DMBuiltins.world_output(DMValue.Format("Player: ", profile.GetVar("character_name"), " (", profile.GetVar("ckey"), "), Karma: ", profile.GetVar("karma"), ", Rounds: ", profile.GetVar("rounds_played")));
            DMBuiltins.world_output((DMValue)"Game Mode & Database test completed successfully!");
            return __dot;
        }

    }

    public class DM_datum_objective : DM_datum
    {
        public override DreamPath TypePath { get { return new DreamPath("/datum/objective"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/datum"); } }

        public DM_datum_objective()
        {
            name = new DMValue("objective");
        }

        public DMValue _ = (DMValue)0;

    }

    public class DM_datum_antagonist_role : DM_datum
    {
        public override DreamPath TypePath { get { return new DreamPath("/datum/antagonist_role"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/datum"); } }

        public DM_datum_antagonist_role()
        {
            name = new DMValue("antagonist_role");
        }

        public DMValue _ = DMBuiltins.list_init(new object[] {  });

        public virtual DMValue add_objective(DMValue d = default(DMValue))
        {
            DMValue __dot = DMValue.Null;
            DMValue O = (new DMValue(new DMObject().InitAndNew()));
            O.SetVar("desc", d);
            this.GetVar("objectives").CallProc("Add", new DMValue[] { O });
            return O;
            return __dot;
        }

    }

    public class DM_datum_player_profile : DM_datum
    {
        public override DreamPath TypePath { get { return new DreamPath("/datum/player_profile"); } }
        public override DreamPath ParentTypePath { get { return new DreamPath("/datum"); } }

        public DM_datum_player_profile()
        {
            name = new DMValue("player_profile");
        }

        public DMValue _ = (DMValue)10;

    }

    public static class Program
    {
        public static int Main(string[] args)
        {
            DMWorld world = DMWorld.Instance;
            world.name = new DMValue("DM App");

            try
            {
                GlobalProcs.main();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Runtime Error: " + ex.Message);
                Console.WriteLine(ex.StackTrace);
                return 1;
            }

            return 0;
        }
    }
}
